<?php

require_once(__DIR__.'/passwords.php');

date_default_timezone_set('UTC');

//General Settings
define('FT_API_REDIRECT_URI', 'http://localhost:9876/');//'http://ec2-18-223-186-53.us-east-2.compute.amazonaws.com');
define('LOG_FILENAME', 'log.txt');
define('BUFFER_LOGGING', false);

//Testing and debug settings
define('DEBUG', true);
define('ONLY_SEND_TO_DEV_WHITELIST', true);
define('USE_FAKE_42_API', false);
define('USE_EXTENDED_WHITELIST', true);
define('USE_ONLY_AUTHORIZATION_CODE_GRANT_TYPE', false);

//TaskMaster task frequencies
define('MINIMUM_SECONDS_BETWEEN_UPDATING_EVENTS', 300); //21600
define('MAXIMUM_SECONDS_BETWEEN_UPDATING_EVENTS', 600); //43200
define('SECONDS_NEEDED_TO_UPDATE_EVENTS', 10);
define('MINIMUM_SECONDS_BETWEEN_UPDATING_EVENT_USERS', 30); //3000
define('MAXIMUM_SECONDS_BETWEEN_UPDATING_EVENT_USERS', 60); //4200
define('SECONDS_NEEDED_TO_UPDATE_EVENT_USERS', 30);
define('MINIMUM_SECONDS_BETWEEN_UPDATING_SLACK_DIRECTORY', 2419200);
define('MAXIMUM_SECONDS_BETWEEN_UPDATING_SLACK_DIRECTORY', 2592000);
define('SECONDS_NEEDED_TO_UPDATE_SLACK_DIRECTORY', 300);
define('MINIMUM_SECONDS_BETWEEN_REFRESHING_AUTHENTICATION', 3600);
define('MAXIMUM_SECONDS_BETWEEN_REFRESHING_AUTHENTICATION', 6500);
define('SECONDS_NEEDED_TO_REFRESH_AUTHENTICATION', 2);


?>
